### ISSUE TITLE
Breaking change in 0.21.4 (#1339)

### ISSUE THREAD

**Issue by Jarema** [rustls/rustls#1352]
Just released rustls 0.21.4 introduces a breaking change in PR #1339 

Unfortunately, it breaks the [async-nats](https://crates.io/crates/async-nats) client (does not compile anymore), which relies on 

```
tokio-rustls = "0.24"
```

With the assumption that semver patch release will not introduce any breaking changes.

The error is:

```
   Compiling async-nats v0.29.0
error[E0282]: type annotations needed
  --> /[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-nats-0.29.0/src/tls.rs:69:20
   |
69 |         root_store.add_parsable_certificates(
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `C` declared on the method `add_parsable_certificates`

For more information about this error, try `rustc --explain E0282`.
error: could not compile `async-nats` (lib) due to previous error
```

and related code snippet: https://github.com/nats-io/nats.rs/blob/main/async-nats/src/tls.rs#L69-L81

That might have a significant impact on us.

Related issue: https://github.com/nats-io/nats.rs/issues/1017

**Comment by cpu** [comment]
I've published v0.21.5 with the breaking change reverted.

**Comment by daxpedda** [comment]
Ah ... it can't figure out the type because `Vec` has two `AsRef` implementations ([[1]](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-AsRef%3CVec%3CT,+A%3E%3E-for-Vec%3CT,+A%3E), [[2]](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-AsRef%3C%5BT%5D%3E-for-Vec%3CT,+A%3E)) and both would actually work in this case.

I was the author of that PR, apologies!

**Comment by cpu** [comment]
Going to close this one out w/ the assumption .5 fixed the issue. Thanks everyone!
