### ISSUE TITLE
rustls v0.23.24/25 break builds in linux/github-ci

### ISSUE THREAD

**Issue by Licenser** [rustls/rustls#2386]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**
With after the upgrade from rustls 0.23.23 to 0.23.24 and then 0.23.25 building cargo-lambda on linux (guthub CI) fails with an type error:

```
   Compiling rustls-platform-verifier v0.4.0
error[E0277]: the trait bound `webpki::Error: std::error::Error` is not satisfied
Error:    --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-platform-verifier-0.4.0/src/verification/others.rs:234:40
    |
234 |             other_err.0.downcast_ref::<webpki::Error>()
    |                         ------------   ^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `webpki::Error`
    |                         |
    |                         required by a bound introduced by this call
    |
note: required by a bound in `<(dyn std::error::Error + Send + Sync + 'static)>::downcast_ref`
   --> /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/error.rs:271:5
```

**To Reproduce**
1. run `cargo install cargo-lambda` on in a github action (it might happen in other linux environments too I can not verify that)

**Applicable Version(s)**

0.23.24 and 0.23.25

**Expected behavior**

a patch version update does not break builds

**Comment by cpu** [comment]
See https://github.com/rustls/rustls-platform-verifier/releases/tag/v%2F0.5.1

The breakage is from `rustls-platform-verifier`. Update it to 0.5.1.

**Comment by djc** [comment]
(This is a duplicate of https://github.com/rustls/rustls-platform-verifier/issues/164.)
